export interface WordPair {
  civilian: string
  undercover: string
  category: string
}

export const WORD_PAIRS: WordPair[] = [
  { civilian: 'Beach', undercover: 'Ocean', category: 'Places' },
  { civilian: 'Coffee', undercover: 'Tea', category: 'Drinks' },
  { civilian: 'Pizza', undercover: 'Burger', category: 'Food' },
  { civilian: 'Cat', undercover: 'Dog', category: 'Animals' },
  { civilian: 'Doctor', undercover: 'Nurse', category: 'Jobs' },
  { civilian: 'Winter', undercover: 'Autumn', category: 'Seasons' },
  { civilian: 'Guitar', undercover: 'Violin', category: 'Instruments' },
  { civilian: 'Airplane', undercover: 'Helicopter', category: 'Travel' },
  { civilian: 'Cinema', undercover: 'Theatre', category: 'Places' },
  { civilian: 'Rain', undercover: 'Snow', category: 'Weather' },
  { civilian: 'Soccer', undercover: 'Basketball', category: 'Sports' },
  { civilian: 'Bicycle', undercover: 'Motorbike', category: 'Travel' },
  { civilian: 'Apple', undercover: 'Pear', category: 'Fruit' },
  { civilian: 'Sun', undercover: 'Moon', category: 'Sky' },
  { civilian: 'Library', undercover: 'Bookstore', category: 'Places' },
  { civilian: 'Camera', undercover: 'Mirror', category: 'Objects' },
  { civilian: 'Hotel', undercover: 'Hostel', category: 'Travel' },
  { civilian: 'Chess', undercover: 'Checkers', category: 'Games' },
  { civilian: 'Piano', undercover: 'Keyboard', category: 'Instruments' },
  { civilian: 'Passport', undercover: 'Ticket', category: 'Travel' },
  { civilian: 'Umbrella', undercover: 'Raincoat', category: 'Objects' },
  { civilian: 'Bread', undercover: 'Cake', category: 'Food' },
  { civilian: 'Mountain', undercover: 'Volcano', category: 'Nature' },
  { civilian: 'Painting', undercover: 'Photograph', category: 'Art' },
  { civilian: 'Whale', undercover: 'Shark', category: 'Animals' },
  { civilian: 'Letter', undercover: 'Email', category: 'Messages' },
  { civilian: 'Firefighter', undercover: 'Police Officer', category: 'Jobs' },
  { civilian: 'Vampire', undercover: 'Zombie', category: 'Monsters' },
  { civilian: 'Pirate', undercover: 'Ninja', category: 'Characters' },
  { civilian: 'Robot', undercover: 'Alien', category: 'Characters' },
  { civilian: 'Pillow', undercover: 'Blanket', category: 'Home' },
  { civilian: 'Clock', undercover: 'Calendar', category: 'Objects' },
  { civilian: 'Glasses', undercover: 'Sunglasses', category: 'Objects' },
  { civilian: 'Pencil', undercover: 'Marker', category: 'Stationery' },
  { civilian: 'Hospital', undercover: 'Pharmacy', category: 'Places' },
  { civilian: 'Desert', undercover: 'Jungle', category: 'Nature' },
  { civilian: 'Ice Cream', undercover: 'Yogurt', category: 'Dessert' },
  { civilian: 'Wedding', undercover: 'Birthday', category: 'Events' },
  { civilian: 'Submarine', undercover: 'Spaceship', category: 'Vehicles' },
  { civilian: 'Detective', undercover: 'Spy', category: 'Characters' },
  { civilian: 'Toothbrush', undercover: 'Comb', category: 'Home' },
  { civilian: 'Backpack', undercover: 'Suitcase', category: 'Travel' },
  { civilian: 'Lighthouse', undercover: 'Windmill', category: 'Places' },
  { civilian: 'Volleyball', undercover: 'Tennis', category: 'Sports' },
  { civilian: 'Shampoo', undercover: 'Soap', category: 'Home' },
  { civilian: 'Clown', undercover: 'Magician', category: 'Characters' },
  { civilian: 'Chocolate', undercover: 'Caramel', category: 'Dessert' },
  { civilian: 'Boat', undercover: 'Raft', category: 'Vehicles' },
  { civilian: 'Telescope', undercover: 'Microscope', category: 'Objects' },
  { civilian: 'Chicken', undercover: 'Duck', category: 'Animals' },
  { civilian: 'Farm', undercover: 'Garden', category: 'Places' },
  { civilian: 'Snowman', undercover: 'Scarecrow', category: 'Characters' },
  { civilian: 'Karaoke', undercover: 'Concert', category: 'Events' },
  { civilian: 'Skateboard', undercover: 'Rollerblades', category: 'Sports' },
  { civilian: 'Lemonade', undercover: 'Juice', category: 'Drinks' },
  { civilian: 'Candle', undercover: 'Lamp', category: 'Home' },
  { civilian: 'Sword', undercover: 'Axe', category: 'Weapons' },
  { civilian: 'Robot Vacuum', undercover: 'Washing Machine', category: 'Home' },
  { civilian: 'Fireworks', undercover: 'Lightning', category: 'Sky' },
  { civilian: 'Sandcastle', undercover: 'Fort', category: 'Places' },
  { civilian: 'Museum', undercover: 'Gallery', category: 'Places' },
  { civilian: 'Popcorn', undercover: 'Chips', category: 'Snacks' },
  { civilian: 'Kite', undercover: 'Balloon', category: 'Toys' },
  { civilian: 'Astronaut', undercover: 'Diver', category: 'Jobs' },
  { civilian: 'Honey', undercover: 'Syrup', category: 'Food' },
  { civilian: 'Trampoline', undercover: 'Swing', category: 'Toys' },
  { civilian: 'Magazine', undercover: 'Newspaper', category: 'Reading' },
  { civilian: 'Pirate Ship', undercover: 'Cruise Ship', category: 'Vehicles' },
  { civilian: 'Makeup', undercover: 'Tattoo', category: 'Style' },
  { civilian: 'Puppy', undercover: 'Kitten', category: 'Animals' },
  { civilian: 'Rainbow', undercover: 'Sunset', category: 'Sky' },
  { civilian: 'Treadmill', undercover: 'Elevator', category: 'Objects' },
  { civilian: 'Noodles', undercover: 'Rice', category: 'Food' },
]

export function pickWordPair(used: string[] = []): WordPair {
  const available = WORD_PAIRS.filter(
    (p) => !used.includes(p.civilian) && !used.includes(p.undercover),
  )
  const pool = available.length > 0 ? available : WORD_PAIRS
  return pool[Math.floor(Math.random() * pool.length)]
}
